In [1]:
from hdf5storage import loadmat

In [2]:
# mat = loadmat("/mnt/C/BCI Dataset/Task1_Matlab/Matlab files/resultsZAB_SR.mat")
mat = loadmat("/home/g4/Documents/BCI_Project/Dataset/Task1_Matlab/Matlab files/resultsZAB_SR.mat")

In [3]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'sentenceData'])

In [4]:
mat["sentenceData"].dtype

dtype([('content', 'O'), ('rawData', 'O'), ('mean_t1', 'O'), ('mean_t2', 'O'), ('mean_a1', 'O'), ('mean_a2', 'O'), ('mean_b1', 'O'), ('mean_b2', 'O'), ('mean_g1', 'O'), ('mean_g2', 'O'), ('mean_t1_sec', 'O'), ('mean_t2_sec', 'O'), ('mean_a1_sec', 'O'), ('mean_a2_sec', 'O'), ('mean_b1_sec', 'O'), ('mean_b2_sec', 'O'), ('mean_g1_sec', 'O'), ('mean_g2_sec', 'O'), ('mean_t1_diff', 'O'), ('mean_t2_diff', 'O'), ('mean_a1_diff', 'O'), ('mean_a2_diff', 'O'), ('mean_b1_diff', 'O'), ('mean_b2_diff', 'O'), ('mean_g1_diff', 'O'), ('mean_g2_diff', 'O'), ('mean_t1_diff_sec', 'O'), ('mean_t2_diff_sec', 'O'), ('mean_a1_diff_sec', 'O'), ('mean_a2_diff_sec', 'O'), ('mean_b1_diff_sec', 'O'), ('mean_b2_diff_sec', 'O'), ('mean_g1_diff_sec', 'O'), ('mean_g2_diff_sec', 'O'), ('word', 'O'), ('omissionRate', 'O'), ('allFixations', 'O'), ('wordbounds', 'O'), ('answer_mean_t1', 'O'), ('answer_mean_t2', 'O'), ('answer_mean_a1', 'O'), ('answer_mean_a2', 'O'), ('answer_mean_b1', 'O'), ('answer_mean_b2', 'O'), ('ans

In [5]:
mat["sentenceData"]["content"][0,1]

array(['Beautifully crafted, engaging filmmaking that should attract upscale audiences hungry for quality and a nostalgic, twisty yarn that will keep them guessing.'],
      dtype='<U156')

In [6]:
res = []
for i in range(mat["sentenceData"]["content"].shape[1]):
    res.append(mat["sentenceData"]["content"][0,i].item())

with open("sentences.txt", "w") as f:
    f.write("\n".join(res))

In [7]:
mat["sentenceData"]["rawData"][0,1]

array([[ 0.31344172,  0.69693404, -0.05696342, ...,  0.05824491,
        -0.53018284, -0.537511  ],
       [ 0.36348966, -0.04016582, -0.22898431, ..., -0.590284  ,
        -0.5384082 , -0.70187634],
       [ 0.89097756,  1.3332819 ,  0.37423965, ...,  0.7662453 ,
        -0.3242263 , -1.0619977 ],
       ...,
       [-0.12457634,  1.5733595 ,  1.6647291 , ...,  0.36703458,
        -0.35501048, -0.8102827 ],
       [-0.12482326,  2.6448221 ,  2.412978  , ...,  1.765022  ,
         0.05571292, -0.5650343 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)

In [8]:
mat["sentenceData"]["rawData"][0,1].shape

(105, 3412)

In [9]:
sentence_id = 1 # 0-399
word_id = 1 # 0-21
mat["sentenceData"]["word"][0,sentence_id][0,word_id].dtype

dtype([('content', 'O'), ('fixPositions', 'O'), ('nFixations', 'O'), ('meanPupilSize', 'O'), ('rawEEG', 'O'), ('rawET', 'O'), ('FFD', 'O'), ('FFD_pupilsize', 'O'), ('FFD_t1', 'O'), ('FFD_t2', 'O'), ('FFD_a1', 'O'), ('FFD_a2', 'O'), ('FFD_b1', 'O'), ('FFD_b2', 'O'), ('FFD_g1', 'O'), ('FFD_g2', 'O'), ('FFD_t1_diff', 'O'), ('FFD_t2_diff', 'O'), ('FFD_a1_diff', 'O'), ('FFD_a2_diff', 'O'), ('FFD_b1_diff', 'O'), ('FFD_b2_diff', 'O'), ('FFD_g1_diff', 'O'), ('FFD_g2_diff', 'O'), ('TRT', 'O'), ('TRT_pupilsize', 'O'), ('TRT_t1', 'O'), ('TRT_t2', 'O'), ('TRT_a1', 'O'), ('TRT_a2', 'O'), ('TRT_b1', 'O'), ('TRT_b2', 'O'), ('TRT_g1', 'O'), ('TRT_g2', 'O'), ('TRT_t1_diff', 'O'), ('TRT_t2_diff', 'O'), ('TRT_a1_diff', 'O'), ('TRT_a2_diff', 'O'), ('TRT_b1_diff', 'O'), ('TRT_b2_diff', 'O'), ('TRT_g1_diff', 'O'), ('TRT_g2_diff', 'O'), ('GD', 'O'), ('GD_pupilsize', 'O'), ('GD_t1', 'O'), ('GD_t2', 'O'), ('GD_a1', 'O'), ('GD_a2', 'O'), ('GD_b1', 'O'), ('GD_b2', 'O'), ('GD_g1', 'O'), ('GD_g2', 'O'), ('GD_t1_di

In [10]:
mat["sentenceData"]["word"][0,1][0,0]["content"]

array(['Beautifully'], dtype='<U11')

In [11]:
mat["sentenceData"]["word"][0,1][0,10]["rawEEG"].shape

(1, 0)

In [12]:
mat["sentenceData"]["word"][0,1][0,10]["nFixations"]

array([], shape=(0, 0), dtype=uint8)

In [13]:
mat["sentenceData"]["word"][0,1]["fixPositions"][0]

array([array([[1, 2]], dtype=uint8), array([[3]], dtype=uint8),
       array([[4, 5, 6]], dtype=uint8), array([[7]], dtype=uint8),
       array([[8]], dtype=uint8), array([[9]], dtype=uint8),
       array([[10]], dtype=uint8), array([[11, 13]], dtype=uint8),
       array([[12, 14]], dtype=uint8), array([[15, 16]], dtype=uint8),
       array([], shape=(0, 0), dtype=uint8), array([[17]], dtype=uint8),
       array([], shape=(0, 0), dtype=uint8), array([[18]], dtype=uint8),
       array([[19]], dtype=uint8), array([[20]], dtype=uint8),
       array([[21]], dtype=uint8), array([], shape=(0, 0), dtype=uint8),
       array([[22]], dtype=uint8), array([[23]], dtype=uint8),
       array([[25]], dtype=uint8), array([[24, 26]], dtype=uint8)],
      dtype=object)

In [14]:
import localizer
import numpy as np
from tqdm import tqdm

In [14]:
mat["sentenceData"]["rawData"].shape

(1, 400)

In [15]:
eeg_signal = mat["sentenceData"]["rawData"][0,2]

localized_eeg = localizer.localize(eeg_signal)

localized_eeg.shape, eeg_signal.shape

((8196, 1722), (105, 1722))

In [16]:
res = np.empty((1, 400), dtype=object)

In [17]:
for i in tqdm(range(400)):
    eeg_signal = mat["sentenceData"]["rawData"][0,i]
    try:
        localized_eeg = localizer.localize(eeg_signal)
        res[0,i] = localized_eeg
    except Exception as e:
        print(f"Error processing sentence {i}: {e}")
        print(eeg_signal.shape)
        res[0,i] = None

  7%|▋         | 27/400 [00:11<02:14,  2.77it/s]

Error processing sentence 27: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 17%|█▋        | 69/400 [00:26<02:43,  2.02it/s]

Error processing sentence 69: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 43%|████▎     | 172/400 [01:11<01:35,  2.38it/s]

Error processing sentence 172: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 46%|████▌     | 182/400 [01:15<01:44,  2.09it/s]

Error processing sentence 182: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 51%|█████     | 204/400 [01:24<01:30,  2.17it/s]

Error processing sentence 204: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)
Error processing sentence 205: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 62%|██████▎   | 250/400 [01:44<01:08,  2.20it/s]

Error processing sentence 250: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


 87%|████████▋ | 349/400 [02:31<00:33,  1.53it/s]

Error processing sentence 349: len(data) (1) does not match len(info["ch_names"]) (105)
(1, 1)


100%|██████████| 400/400 [03:02<00:00,  2.20it/s]


In [18]:
sum(x.nbytes for x in res[0] if x is not None) / (1024**3)  # in GB

58.409548848867416

In [19]:
# np.save("localized_eeg_sentences_ZAB.npy", res, allow_pickle=True)
np.savez("localized_eeg_sentences_ZAB.npz", *res)