In [1]:
from hdf5storage import loadmat

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [9]:
mat = loadmat("/mnt/D/University/Fall 2025/BCI/Dataset/Task1_Preprocessed/ZAB/wordbounds_SNR1_ZAB.mat")

mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'textbounds', 'wordbounds'])

In [10]:
mat["textbounds"].shape, mat["textbounds"].dtype, mat["textbounds"][0,0].shape, mat["textbounds"][0,0].dtype

((1, 250), dtype('O'), (1, 4), dtype('<u2'))

In [11]:
mat["wordbounds"].shape, mat["wordbounds"].dtype, mat["wordbounds"][0,0].shape, mat["wordbounds"][0,0].dtype

((1, 250), dtype('O'), (22, 4), dtype('<f8'))

In [ ]:
mat["textbounds"][0,0], mat["wordbounds"][0,0].max(axis=0)

(array([[ 90,  76, 620, 156]], dtype=uint16),
 array([571.515625, 139.      , 618.      , 154.      ]))

In [5]:
mat = loadmat("/mnt/D/University/Fall 2025/BCI/Dataset/Task1_Preprocessed/ZAB/gip_ZAB_SR2_EEG.mat")

mat["EEG"]["data"].shape

(1, 105, 128531)

In [6]:
mat_eye = loadmat("/mnt/D/University/Fall 2025/BCI/Dataset/Task1_Preprocessed/ZAB/ZAB_SR2_corrected_ET.mat")

mat_eye.keys()

dict_keys(['__header__', '__version__', '__globals__', 'comments', 'colheader', 'data', 'messages', 'eyeevent', 'event'])

In [7]:
mat_eye["data"].shape

(128553, 4)

In [8]:
mat_eye["data"][0]

array([6.110683e+06, 3.971000e+02, 3.091000e+02, 8.720000e+02])